
services:
  dummy-ok:
    image: python:3.11-slim
    container_name: dummy-ok
    command: >
      python -m http.server 8085
    ports:
      - "8085:8085"
      
  otel-collector:
    platform: linux/arm64
    #image: otel/opentelemetry-collector-contrib:0.104.0
    image: otel/opentelemetry-collector-contrib:nightly

    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    environment:
      NEW_RELIC_API_KEY: "${NEW_RELIC_API_KEY}"
      NEW_RELIC_REGION: "${NEW_RELIC_REGION:-US}"
      NEW_RELIC_ENDPOINT: "${NEW_RELIC_ENDPOINT}"
    volumes:
      - ./otel/config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4318:4318"   # OTLP/HTTP receiver (Kong → Collector)
      - "4317:4317"   # OTLP/gRPC receiver (opcional)
      - "13133:13133" # Health check extension
    depends_on:
    - dummy-ok