# ZTNA On-Premise OTel Collector Config
#
# This config is used to collect metrics from the ZTNA On-Premise environment.

extensions:
  health_check:
    endpoint: 0.0.0.0:8080
    path: /health
    check_collector_pipeline:
      enabled: true
      interval: 30s
      exporter_failure_threshold: 3

receivers:
  prometheus:
    config:
      global:
        scrape_interval: 30s
        scrape_timeout: 15s
      scrape_configs:
        - job_name: 'ztna_metrics'
          metrics_path: /metrics

processors:
  memory_limiter:
    check_interval: 10s
    limit_percentage: 75
    spike_limit_percentage: 25

  filter/keep_ztna_and_custom: #Deja pasar sólo métricas "custom_ztna"
    metrics:
      include:
        match_type: regexp
        metric_names:
          - "^custom_ztna_.*$"

  batch: #SOLO PRODUCCIÓN
    timeout: 5s
    send_batch_size: 256
    send_batch_max_size: 512

exporters:
  prometheusremotewrite: #Prometheus Remote Write → New Relic (para scrapeo Prometheus)
    endpoint: "https://metric-api.newrelic.com/prometheus/v1/write"
    headers:
      api-key: 4cab137d561e18308687c7cc5ea9af4aFFFFNRAL
    external_labels:
      prometheus_server: otel-collector-ztna #Nombre del servidor de Prometheus
    compression: none #gzip
    timeout: 60s #SOLO EN PRODUCCIÓN
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 1800s

  logging/debug: #Exportador de logging
    verbosity: detailed

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      processors:
        - memory_limiter
        - filter/keep_ztna_and_custom
        - batch
      exporters: [logging/debug, prometheusremotewrite]