# ZTNA On-Premise OTel Collector Config
#
# This config is used to collect metrics from the ZTNA On-Premise and OCI environment.

extensions:
  health_check:
    endpoint: 0.0.0.0:8080
    path: /health
    check_collector_pipeline:
      enabled: true
      interval: 30s
      exporter_failure_threshold: 3

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'ztna_metrics'
          scrape_interval: 30s
          scrape_timeout: 15s
          metrics_path: /metrics
          static_configs:
            - targets: 
                - 192.168.36.86:60123
                - 192.168.36.87:60123
                - 192.168.36.88:60123
                - 192.168.36.89:60123
                - 172.26.40.1:61000
                - 172.26.40.2:61000
                - 172.26.40.3:61000
                - 172.26.40.4:61000
                - 172.26.40.5:61000
                - 172.26.49.6:61000

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2048
    spike_limit_mib: 512

  batch:
    timeout: 10s
    send_batch_size: 10000

exporters:
  prometheusremotewrite: #Prometheus Remote Write → New Relic (para scrapeo Prometheus)
    endpoint: "https://metric-api.newrelic.com/prometheus/v1/write"
    headers:
      api-key: 4cab137d561e18308687c7cc5ea9af4aFFFFNRAL
    external_labels:
      prometheus_server: otel-collector-ztna #Nombre del servidor de Prometheus
    compression: none #gzip
    timeout: 60s #SOLO EN PRODUCCIÓN
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 1800s

  logging/debug: #Exportador de logging
    verbosity: detailed

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      processors:
        - memory_limiter
        - batch
      exporters: [logging/debug, prometheusremotewrite]